on:
  push:
    paths:
    - 'backend/**'
    - '.github/workflows/git_action_backend.yml'

permissions:
  id-token: write
  contents: read

jobs:
  Updating_backend:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        role-to-assume: arn:aws:iam::339713022110:role/Github-oicd-role
        aws-region: ca-central-1
    
    - name: setup terraform
      uses: hashicorp/setup-terraform@v3
      with: 
       terraform_version: "1.1.7"

    - name: Terraform init
      run: terraform init
      working-directory: backend
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: backend

    
    
